name: Run CumulusCI Deployment

on:
  # Trigger on pull requests to the main branch
  pull_request:
    branches:
      - main
      - feature/*
  # Trigger via workflow dispatch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      # Step 3: Install dependencies (CumulusCI & Robot)
      - name: Install CumulusCI
        run: |
          python -m pip install --upgrade pip
          pip install cumulusci
      - name: Initialize Browser/Playwright
        run: cci robot install_playwright

      # Step 4: Run CumulusCI flow
      - name: Run deploy_solution flow
        env:
          CUMULUSCI_KEYCHAIN: encrypted
        run: |
          cci flow run deploy_solution --org dev
